# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DeleteFiles@1
  displayName: 'Delete JUnit files'
  inputs:
    SourceFolder: testing/junit
    Contents: 'TESTS*.xml'
      
- task: Npm@1
  displayName: 'Install Node'
  inputs:
    command: install
    workingDir: testing

- task: Npm@1
  displayName: 'Building'
  inputs:
    command: custom
    customCommand: run build
    workingDir: testing

- task: Npm@1
  displayName: 'Testing'
  inputs:
    command: custom
    customCommand: run test -- --watch=false --code-coverage --browser ChromeHeadless
    workingDir: testing

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'testing/dist'

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage Angular results'
  condition: succeededOrFailed() # Run this step, even if previous steps fail
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: 'testing/coverage/cobertura-coverage.xml'
    reportDirectory: testing/coverage
    failIfCoverageEmpty: true
    
- task: PublishTestResults@2
  displayName: 'Publish Angular test results'
  condition: succeededOrFailed()
  inputs:
    searchFolder: $(System.DefaultWorkingDirectory)/testing/junit
    testRunTitle: Angular
    testResultsFormat: JUnit
    testResultsFiles: "**/TESTS*.xml"

